### ISSUE TITLE
Output?

### ISSUE THREAD

**Issue by junyismad** [BankkRoll/NFTGEN-nft-generator#4]
1st issue was that the ora package wasn't installed, once installed everything worked, it generated 1000 in about 20-25 minutes with 3 layers but nothing shows up in the output folder. otherwise, thanks for the update, i'm looking forward to a flawless run

**Comment by BankkRoll** [comment]
I apologize for any inconvenience caused. Recently, I made some adjustments to address similar concerns, so please verify that you're using the most recent version as this might solve your issues. I'm planning a comprehensive overhaul to improve user experience and functionality, though due to current time constraints, this won't be immediate. Your understanding and patience are greatly appreciated during this period.
