### ISSUE TITLE
 Cant generate gif 

### ISSUE THREAD

**Issue by samaya-smg** [BankkRoll/NFTGEN-nft-generator#5]
ERROR. failed to generate GIF xx :The first argument must be an object
I got that error, can u help me?
This generate work for image only

**Comment by BankkRoll** [comment]
I apologize for any inconvenience caused, also It does generate gifs. Recently, I made some adjustments to address similar concerns, so please verify that you're using the most recent version as this might solve your issues. I'm planning a comprehensive overhaul to improve user experience and functionality, though due to current time constraints, this won't be immediate. Your understanding and patience are greatly appreciated during this period.

**Comment by BankkRoll** [comment]
Hello, @samaya-smg 

I've just rolled out some important updates to the code that I think you'll appreciate. The latest version includes key bug fixes, performance optimizations, and adjustments to the intensity of the processing, all designed to make the experience smoother and more flexible for you.

I strongly encourage you to use this new version as it's been improved considerably based on the feedback received.

Thank you for your patience and understanding. Your feedback is crucial in my development journey.
