### ISSUE TITLE
canvas and sharp library conflict

### ISSUE THREAD

**Issue by j-paterson** [BankkRoll/NFTGEN-nft-generator#9]
npm start

> nftgen@4.2.2 start /Users/jessepaterson/Projects/NFTGEN-nft-gif-generator
> node --experimental-modules generate.mjs

objc[55996]: Class GNotificationCenterDelegate is implemented in both /Users/jessepaterson/Projects/NFTGEN-nft-gif-generator/node_modules/canvas/build/Release/libgio-2.0.0.dylib (0x110e4d6b0) and /Users/jessepaterson/Projects/NFTGEN-nft-gif-generator/node_modules/@img/sharp-libvips-darwin-x64/lib/libvips-cpp.42.dylib (0x1154a4770). One of the two will be used. Which one is undefined.
file:///Users/jessepaterson/Projects/NFTGEN-nft-gif-generator/node_modules/ora/node_modules/string-width/index.js:5
const segmenter = new Intl.Segmenter();
                  ^

TypeError: Intl.Segmenter is not a constructor
    at file:///Users/jessepaterson/Projects/NFTGEN-nft-gif-generator/node_modules/ora/node_modules/string-width/index.js:5:19
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nftgen@4.2.2 start: `node --experimental-modules generate.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nftgen@4.2.2 start script.

**Comment by BankkRoll** [comment]
hey @j-paterson  sorry for the delay. Ensure you're running a version of Node.js that supports Intl.Segmenter. Intl.Segmenter is supported in Node.js versions 14 and above. But the issue seems to be originating from the `ora` package, so reinstalling it might help resolve the problem.

Please try this in your project directory:
`npm install ora`
`npm run start`

Let me know if this resolves the issue or if you encounter any further problems.
